# Generated by Django 5.2.12 on 2026-03-11 06:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommended_topic', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.FloatField(default=0.0)),
                ('weak_areas', models.JSONField(default=list)),
                ('strong_areas', models.JSONField(default=list)),
                ('predicted_grade', models.CharField(blank=True, max_length=5)),
                ('topic_scores', models.JSONField(default=dict)),
                ('trend_data', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_analytics',
            },
        ),
    ]
