# Generated by Django 5.2.12 on 2026-03-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_add_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='linear-gradient(135deg, #6366f1, #8b5cf6)', help_text='CSS gradient for course cards, e.g. linear-gradient(135deg, #6366f1, #8b5cf6)', max_length=100),
        ),
    ]
